filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'

processors:
- add_docker_metadata:
    host: "unix:///var/run/docker.sock"

- decode_json_fields:
    fields: ["message"]
    target: "json"
    overwrite_keys: true

- drop_event:
    when.and:
      - not.equals:
          container.labels.althingi_service: "aggregator"
      - not.equals:
          container.labels.althingi_service: "source"
      - not.equals:
          container.labels.althingi_service: "store"
      - not.equals:
          container.labels.althingi_service: "server"
      - not.equals:
          container.labels.althingi_service: "messages"


output.logstash:
  hosts: ["logstash:5044"]