name: CI/CD actions
on: [push]
jobs:

  build-deploy-init:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ENV=production
          file: Dockerfile.init
          labels: |
            git_commit=${{ github.sha }}
            github_run_id=${{ github.run_id }}
            github_run_number=${{ github.run_number }}
          tags: ${{ secrets.DOCKER_USERNAME }}/althingi-search-init:${{ github.run_id }}, ${{ secrets.DOCKER_USERNAME }}/althingi-search-init:latest
      -
        name: Build versioning
        run: |
            echo outputs.digest: ${{ steps.docker_build.outputs.digest }}
            echo github.sha: ${{ github.sha }}
            echo github.run_number ${{ github.run_number }}
            echo github.run_id: ${{ github.run_id }}
      -
        name: Deploy container to server
        uses: appleboy/ssh-action@master
        with:
          script: ls -a
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}

  build-deploy-metricbeat:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ENV=production
          file: Dockerfile.metricbeat
          labels: |
            git_commit=${{ github.sha }}
            github_run_id=${{ github.run_id }}
            github_run_number=${{ github.run_number }}
          tags: ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-metricbeat:${{ github.run_id }}, ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-metricbeat:latest
      -
        name: Build versioning
        run: |
            echo outputs.digest: ${{ steps.docker_build.outputs.digest }}
            echo github.sha: ${{ github.sha }}
            echo github.run_number ${{ github.run_number }}
            echo github.run_id: ${{ github.run_id }}
      -
        name: Deploy container to server
        uses: appleboy/ssh-action@master
        with:
          script: ls -a
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}

  build-deploy-filebeat:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ENV=production
          file: Dockerfile.filebeat
          labels: |
            git_commit=${{ github.sha }}
            github_run_id=${{ github.run_id }}
            github_run_number=${{ github.run_number }}
          tags: ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-filebeat:${{ github.run_id }}, ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-filebeat:latest
      -
        name: Build versioning
        run: |
            echo outputs.digest: ${{ steps.docker_build.outputs.digest }}
            echo github.sha: ${{ github.sha }}
            echo github.run_number ${{ github.run_number }}
            echo github.run_id: ${{ github.run_id }}
      -
        name: Deploy container to server
        uses: appleboy/ssh-action@master
        with:
          script: ls -a
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}

  build-deploy-logstash:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          build-args: ENV=production
          file: Dockerfile.logstash
          labels: |
            git_commit=${{ github.sha }}
            github_run_id=${{ github.run_id }}
            github_run_number=${{ github.run_number }}
          tags: ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-logstash:${{ github.run_id }}, ${{ secrets.DOCKER_USERNAME }}/althingi-monitor-logstash:latest
      -
        name: Build versioning
        run: |
            echo outputs.digest: ${{ steps.docker_build.outputs.digest }}
            echo github.sha: ${{ github.sha }}
            echo github.run_number ${{ github.run_number }}
            echo github.run_id: ${{ github.run_id }}
      -
        name: Deploy container to server
        uses: appleboy/ssh-action@master
        with:
          script: ls -a
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{ secrets.SSH_KEY }}
